//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adeudo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adeudo()
        {
            this.AdeudoContribuyentes = new HashSet<AdeudoContribuyente>();
        }
    
        public int IdAdeudo { get; set; }
        public string Periodo { get; set; }
        public string Concepto { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdeudoContribuyente> AdeudoContribuyentes { get; set; }
    }
}
