//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adeudo
    {
        public int IdAdeudo { get; set; }
        public int IdContribuyente { get; set; }
        public string Periodo { get; set; }
        public string Concepto { get; set; }
        public decimal MontoOriginal { get; set; }
        public decimal Recargo { get; set; }
        public decimal OtrosCargos { get; set; }
        public Nullable<decimal> TotalAdeudo { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual Contribuyente Contribuyente { get; set; }
    }
}
