//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribuyente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contribuyente()
        {
            this.Adeudoes = new HashSet<Adeudo>();
        }
    
        public int IdContribuyente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdTarifa { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaUltimoAviso { get; set; }
        public Nullable<System.DateTime> FechaLimitePago { get; set; }
        public Nullable<int> DiasGracia { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Tarifa Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adeudo> Adeudoes { get; set; }
    }
}
