//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCPSAPEntities : DbContext
    {
        public SCPSAPEntities()
            : base("name=SCPSAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Tarifa> Tarifas { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRols { get; set; }
        public virtual DbSet<UsuarioSistema> UsuarioSistemas { get; set; }
        public virtual DbSet<AdeudoContribuyente> AdeudoContribuyentes { get; set; }
        public virtual DbSet<DetallePago> DetallePagos { get; set; }
        public virtual DbSet<Adeudo> Adeudos { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Material> Materiales { get; set; }
        public virtual DbSet<MovimientoInventario> MovimientoInventarios { get; set; }
        public virtual DbSet<Egreso> Egresos { get; set; }
        public virtual DbSet<Calle> Calles { get; set; }
        public virtual DbSet<Contribuyente> Contribuyentes { get; set; }
    }
}
