//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventario
    {
        public int IdMovimiento { get; set; }
        public int IdMaterial { get; set; }
        public string TipoMovimiento { get; set; }
        public string Observaciones { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public int IdUsuarioSistema { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual UsuarioSistema UsuarioSistema { get; set; }
    }
}
