//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.DetallePagoes = new HashSet<DetallePago>();
        }
    
        public int IdPago { get; set; }
        public int IdContribuyente { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal TotalPagado { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<int> IdUsuarioSistema { get; set; }
    
        public virtual Contribuyente Contribuyente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePago> DetallePagoes { get; set; }
        public virtual UsuarioSistema UsuarioSistema { get; set; }
    }
}
